### ISSUE TITLE
Sam

### ISSUE THREAD

**Issue by billyrturner** [Jemila-Abdulai/software-engineering-2#1]
he is old

**Comment by FebruaryRain** [comment]
Plan:

On reflection, this issue a borked. The hardware is out of date and the software isn't supported.

Closing, not fixing.

**Comment by billyrturner** [comment]
After careful consideration and multiple spike tickets, we have come to the conclusion that this issue is unsolvable.

**Comment by billyrturner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/nXkiPbtU/1-test)
