### ISSUE TITLE
Setup GitHub actions for testing, building container, pushing to docker hub etc

### ISSUE THREAD

**Issue by billyrturner** [Jemila-Abdulai/software-engineering-2#15]

**Comment by billyrturner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [setup GitHub actions for testing, building container, pushing to docker hub, etc](https://trello.com/c/HkRQ5KhJ/6-setup-github-actions-for-testing-building-container-pushing-to-docker-hub-etc)

**Comment by Allaina-Santhosh** [comment]
@ashketchupppp has created actions for creating the dashboard. Working on/ researching how to create action to test dashboard and deploy to docker.

- [ ] create docker container for dashboard
- [ ] create action for test and deploy

**Comment by Allaina-Santhosh** [comment]
Created a test github action file in Docker v2 branch - doesn't work at the moment
