### ISSUE TITLE
Fix the sensors

### ISSUE THREAD

**Issue by ashketchupppp** [Jemila-Abdulai/software-engineering-2#5]
Currently the sensors are broken, the linting brings up many errors and the tests don't even run.

Valve pls fix

**Comment by FebruaryRain** [comment]
As discussed in the last 2 meetings, we are done with this, prior PRs have resolved the issues we originally had and the commented out tests simply aren't worth fixing as they appear to relate to areas of the code we are not interested in as we don't use them.
Closing.
