### ISSUE TITLE
Wireframe the Dashboard

### ISSUE THREAD

**Issue by FebruaryRain** [Jemila-Abdulai/software-engineering-2#8]
As a developer, I want to develop the dashboard with a wireframe in front of me, so that I have a plan on what we are hoping to accomplish and know that what is produced is going to be what is agreed.

We need to decide what the dashboard should look like before we start programming it. 

We should sit down around a draw.io or similar tool to provide a rough diagram of the relevant elements, where they sit on the page, what we want to show. 

This may require that we find out what data we are being provided to be able to find appropriate visualisations.

**Comment by FebruaryRain** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sam Oldness Test](https://trello.com/c/nXkiPbtU/1-sam-oldness-test)

**Comment by billyrturner** [comment]
@FebruaryRain @Allaina-Santhosh @Jemila-Abdulai @ashketchupppp wonder if we try and get this one done as a group, after the agile ceremonies are out of the way on Thursday?

**Comment by FebruaryRain** [comment]
We did this in a meeting. Done.
